title: Bin Li
description: >
  <br><br>
  <img src="/binli.jpg" width="60%">
  <br />
  <strong>Master Student</strong>
  <br />
  Department of Control and Systems Engineering
  <br />
  Nanjing University
  <br />
  Email: <a href="mailto:binli@smail.nju.edu.cn" target="_blank">binli@smail.nju.edu.cn</a>
theme: jekyll-theme-minimal
