title: Bin Li
description: >
  <br><br>
  <img src="/binli.jpg" width="60%">
  <br />
  <strong>Master Student</strong>
  <br />
  <strong>Department of Control and Systems Engineering</strong>
  <br />
  <strong>Nanjing University</strong>
  <br />
  <strong>Email:</strong> <a href="mailto:binli@smail.nju.edu.cn" target="_blank">binli@smail.nju.edu.cn</a>
theme: jekyll-theme-minimal
